# Generated by Django 4.1 on 2022-08-27 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_no', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('Area_Name', models.CharField(max_length=100, unique=True, verbose_name='Area Name')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_no', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('Category_Name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='GSTMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_no', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('Head', models.CharField(max_length=100, unique=True, verbose_name='Head')),
                ('HSN_SAC', models.CharField(max_length=100, verbose_name='HSN SAC')),
                ('gst', models.BooleanField(default=False, verbose_name='GST Applicable')),
            ],
        ),
        migrations.CreateModel(
            name='PlotFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_no', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('Plot_Flag_Name', models.CharField(max_length=100, unique=True, verbose_name='Plot Flag Name')),
            ],
        ),
        migrations.CreateModel(
            name='PlotName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_no', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('Plot_Name', models.CharField(max_length=100, unique=True, verbose_name='Plot Name')),
            ],
        ),
        migrations.CreateModel(
            name='Plottype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_no', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('Plottype', models.CharField(max_length=100, unique=True, verbose_name='Plot Type')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_no', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('Project_Name', models.CharField(max_length=100, unique=True, verbose_name='Project Name')),
            ],
        ),
        migrations.CreateModel(
            name='SectorName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_no', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('Sector_Name', models.CharField(max_length=100, verbose_name='Sector Name')),
                ('ProjectName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empdatabase.projectname', verbose_name='Project Name')),
            ],
        ),
        migrations.CreateModel(
            name='PlotMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_no', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('Plot_no', models.IntegerField(verbose_name='Plot Number')),
                ('Plot_size', models.FloatField(verbose_name='Plot Size')),
                ('Extra_Land', models.CharField(blank=True, max_length=100, null=True, verbose_name='Extra Land')),
                ('Type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Type')),
                ('Tag', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tag')),
                ('Flag', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empdatabase.plotflag', verbose_name='Plot Flag')),
                ('Plot_Area', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='empdatabase.areaname', verbose_name='Plot Area')),
                ('Plot_Category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='empdatabase.categoryname', verbose_name='Plot Category')),
                ('Plot_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='empdatabase.plottype', verbose_name='Plot Type')),
                ('Project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='empdatabase.projectname', verbose_name='Project')),
                ('Sector', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='empdatabase.sectorname', verbose_name='Sector')),
            ],
        ),
        migrations.CreateModel(
            name='MasterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Full Name')),
                ('user_level', models.CharField(max_length=100, verbose_name='User Level')),
                ('mobile', models.CharField(max_length=14, unique=True, verbose_name='Mobile Number')),
                ('user_key', models.CharField(max_length=100, verbose_name='User Key')),
                ('user_lock', models.BooleanField(default=False, verbose_name='User Lock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Name')),
            ],
        ),
    ]
